galaxy_info:
  author: thomaslochet
  description: WordPress installation and configuration role
  company: supdevinci
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: Ubuntu
      versions:
        - bionic
        - focal
        - jammy

dependencies: []
