---
- name: Update system packages
  ansible.builtin.package:
    name: "*"
    state: latest
  when: ansible_distribution in ["Ubuntu", "Rocky"]

- name: Install required packages (Debian/Ubuntu)
  ansible.builtin.apt:
    name:
      - apache2
      - php
      - libapache2-mod-php
      - php-mysql
      - mariadb-server
      - python3-pymysql
      - wget
      - unzip
    state: present
    update_cache: yes
  when: ansible_facts['os_family'] == 'Debian'

- name: Install required packages (RedHat/Rocky)
  ansible.builtin.dnf:
    name:
      - httpd
      - php
      - php-mysqlnd
      - mariadb-server
      - python3-PyMySQL
      - wget
      - unzip
    state: present
  when: ansible_facts['os_family'] == 'RedHat'
